name: CI

on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:

jobs:

  ci:
    name: Analyze the libs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Configure
        run: dart pub global activate melos

      # TODO: Run the `generate` script.
      #       Installing `openapi-generator` with all Java deps takes a lot of time.
      #       Let's find some lighter alternative.
      #       Till then we have to always make sure files are properly regenerated.

      - name: Analyze
        run: |
          melos run packages
          melos run check

  tag:
    name: Tag
    needs: ci
    uses: transpaer/github-workflows/.github/workflows/tag-dart.yml@v0.1.0
    permissions:
      contents: write
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
